src/Entity/Jewelry.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;

/**
 * @ORM\Entity(repositoryClass="App\Repository\JewelryRepository")
 */
class Jewelry
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     */
    private $reference;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $sale = false;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $category;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->name);
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getReference(): ?int
    {
        return $this->reference;
    }

    public function setReference(int $reference): self
    {
        $this->reference = $reference;

        return $this;
    }

    public function getFormattedReference(): string
    {
        return number_format($this->reference, 0, '', '-');
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getFormattedPrice(): string
    {
        return number_format($this->price, 0, '', ' ');
    }

    public function getSale(): ?bool
    {
        return $this->sale;
    }

    public function setSale(bool $sale): self
    {
        $this->sale = $sale;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(string $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }
}

src/Form/JewelryType.php
<?php

namespace App\Form;

use App\Entity\Jewelry;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class JewelryType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('description')
            ->add('reference')
            ->add('price')
            ->add('sale')
            ->add('category')
            ->add('image')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Jewelry::class,
            'translation_domain' => 'forms'
        ]);
    }
}

src/Controller/JewelryController.php
<?php

namespace App\Controller;

use App\Entity\Jewelry;
use App\Repository\JewelryRepository;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class JewelryController extends AbstractController
{
  /**
   * @var JewelryRepository
   */
  private $repository;

  /**
   * @var ObjectManager
   */
  private $em;

  public function __construct(JewelryRepository $repository, ObjectManager $em)
  {
    $this->repository = $repository;
    $this->em = $em;
  }

  /**
   * @Route("/", name="jewelry.index")
   * @param JewelryRepository $repository
   * @return Response
   */
  public function index(JewelryRepository $repository): Response
  {
    // $jewelry = $repository->findLatest();
    $lastest = $repository->findLatest();
    $all = $repository->findAll();
    $sale = $repository->findBySale();
    $necklaces = $repository->findByCategory('necklaces');
    $earrings = $repository->findByCategory('earrings');
    $bracelets = $repository->findByCategory('bracelets');

    // $jewelry = $repository->findByCategory('jewelry');
    //$jewelry = $this->repository->findOneBy(['category' => 'watch']);
    //dump($jewelry);
    // $category = $repository->getCategory();
    // dump($category);
    // 'category' => $jewelry->getCategory()
    
    return $this->render('client/jewelry/index.html.twig', [
      'lastest' => $lastest,
      'all' => $all,
      'sale' => $sale,
      'necklaces' => $necklaces,
      'earrings' => $earrings,
      'bracelets' => $bracelets,
      'active_menu' => 'jewelry'
    ]);
  }

  /**
   * @Route("/jewelry/{category}/{slug}-{id}", name="client.jewelry.single", requirements={"slug": "[a-z0-9\-]*"})
   * @param Jewelry $jewelry
   * @return Response
   */
  public function single(Jewelry $jewelry, string $slug): Response
  {
    if ($jewelry->getSlug() !== $slug ) {
      return $this->redirectToRoute('client.jewelry.single', [
        'id' => $jewelry->getId(),
        'slug' => $jewelry->getSlug(),
        'category' => $jewelry->getCategory()
      ], 301);
    }
    return $this->render('client/jewelry/single.html.twig', [
      'jewelry' => $jewelry
    ]);
  }

  // /**
  //  * @Route("/jewelry/bracelets/{slug}-{id}", name="client.jewelry.single", requirements={"slug": "[a-z0-9\-]*"})
  //  * @param Jewelry $jewelry
  //  * @return Response
  //  */
  // public function single(Jewelry $jewelry, string $slug): Response
  // {
  //   if ($jewelry->getSlug() !== $slug ) {
  //     return $this->redirectToRoute('client.jewelry.single', [
  //       'id' => $jewelry->getId(),
  //       'slug' => $jewelry->getSlug()
  //     ], 301);
  //   }
  //   return $this->render('client/jewelry/single.html.twig', [
  //     'jewelry' => $jewelry,
  //     'active_menu' => 'bracelets'
  //   ]);
  // }
}

templates/client/jewelry/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}Jewelry{% endblock %}
{% block body %}
<main>
  <h1 class="title">Lastest <span>({{ lastest|length }})</span></h1>
  <div class="jewelry">
    {% for jewel in lastest %}
    <div class="jewel">
      <a href="{{ path('client.jewelry.single', { id: jewel.id, slug: jewel.slug, category: jewel.category|lower }) }}" class="jewel-inside">
        <img class="jewel-image" src="http://picsum.photos/id/{{ jewel.image }}/467/467" alt="{{ jewel.name }}">
        <div class="jewel-caption">
          <h3 class="jewel-title">{{ jewel.name }}</h3>
          <strong class="jewel-price">{{ jewel.formattedPrice }} €</strong>
        </div>
      </a>
    </div>
    {% endfor %}
  </div>
  <h2 class="title">Sales <span>({{ sale|length }})</span></h2>
  <div class="jewelry">
    {% for jewel in sale %}
    <div class="jewel">
      <a href="{{ path('client.jewelry.single', { id: jewel.id, slug: jewel.slug, category: jewel.category|lower }) }}" class="jewel-inside">
        <img class="jewel-image" src="http://picsum.photos/id/{{ jewel.image }}/467/467" alt="{{ jewel.name }}">
        <div class="jewel-caption">
          <h3 class="jewel-title">{{ jewel.name }}</h3>
          <strong class="jewel-price">{{ jewel.formattedPrice }} €</strong>
        </div>
      </a>
    </div>
    {% endfor %}
  </div>
  <h2 class="title">Necklaces and pendants <span>({{ necklaces|length }})</span></h2>
  <div class="jewelry">
    {% for jewel in necklaces %}
    <div class="jewel">
      <a href="{{ path('client.jewelry.single', { id: jewel.id, slug: jewel.slug, category: jewel.category|lower }) }}" class="jewel-inside">
        <img class="jewel-image" src="http://picsum.photos/id/{{ jewel.image }}/467/467" alt="{{ jewel.name }}">
        <div class="jewel-caption">
          <h3 class="jewel-title">{{ jewel.name }}</h3>
          <strong class="jewel-price">{{ jewel.formattedPrice }} €</strong>
        </div>
      </a>
    </div>
    {% endfor %}
  </div>
  <h2 class="title">The earrings <span>({{ earrings|length }})</span></h2>
  <div class="jewelry">
    {% for jewel in earrings %}
    <div class="jewel">
      <a href="{{ path('client.jewelry.single', { id: jewel.id, slug: jewel.slug, category: jewel.category|lower }) }}" class="jewel-inside">
        <img class="jewel-image" src="http://picsum.photos/id/{{ jewel.image }}/467/467" alt="{{ jewel.name }}">
        <div class="jewel-caption">
          <h3 class="jewel-title">{{ jewel.name }}</h3>
          <strong class="jewel-price">{{ jewel.formattedPrice }} €</strong>
        </div>
      </a>
    </div>
    {% endfor %}
  </div>
  <h2 class="title">The bracelets <span>({{ bracelets|length }})</span></h2>
  <div class="jewelry">
    {% for jewel in bracelets %}
    <div class="jewel">
      <a href="{{ path('client.jewelry.single', { id: jewel.id, slug: jewel.slug, category: jewel.category|lower }) }}" class="jewel-inside">
        <img class="jewel-image" src="http://picsum.photos/id/{{ jewel.image }}/467/467" alt="{{ jewel.name }}">
        <div class="jewel-caption">
          <h3 class="jewel-title">{{ jewel.name }}</h3>
          <strong class="jewel-price">{{ jewel.formattedPrice }} €</strong>
        </div>
      </a>
    </div>
    {% endfor %}
  </div>
  <h2 class="title">All <span>({{ all|length }})</span></h2>
  <div class="jewelry">
    {% for jewel in all %}
    <div class="jewel">
      <a href="{{ path('client.jewelry.single', { id: jewel.id, slug: jewel.slug, category: jewel.category|lower }) }}" class="jewel-inside">
        <img class="jewel-image" src="http://picsum.photos/id/{{ jewel.image }}/467/467" alt="{{ jewel.name }}">
        <div class="jewel-caption">
          <h3 class="jewel-title">{{ jewel.name }}</h3>
          <strong class="jewel-price">{{ jewel.formattedPrice }} €</strong>
        </div>
      </a>
    </div>
    {% endfor %}
  </div>
</main>
{% endblock %}

templates/client/jewelry/single.html.twig
{% extends 'base.html.twig' %}
{% block title jewelry.name %}
{% block body %}
<main>
  <div class="columns">
    <div class="column">
      <img class="jewel-image" src="http://picsum.photos/id/{{ jewelry.image }}/467/467" alt="{{ jewelry.name }}">
      <span class="column-reference">ref {{ jewelry.formattedreference }}</span>
    </div>
    <div class="column">
      <h1 class="column-title">{{ jewelry.name }}</h1>
      <span class="column-category">{{ jewelry.category }}</span>
      <strong class="column-price">{{ jewelry.formattedPrice }} €</strong>
      <p class="column-description">{{ jewelry.description }}</p>
    </div>
  </div>
</main>
{% endblock %}